TESTS_ENVIRONMENT += \
 TIMEOUT="$(TIMEOUT)" \
 MKTEMP="$(MKTEMP)"

check_PROGRAMS += \
 tests/mobject-connect-test \
 tests/mobject-client-test \
 tests/mobject-aio-test

# don't include rados programs in make check
if HAVE_RADOS
noinst_PROGRAMS += \
 tests/rados-mobject-connect-test
endif

TESTS += \
 tests/mobject-connect-test.sh \
 tests/mobject-client-test.sh

EXTRA_DIST += \
 tests/mobject-connect-test.sh \
 tests/mobject-client-test.sh \
 tests/mobject-test-util.sh

tests_mobject_connect_test_LDADD = src/client/libmobject-store.la ${CLIENT_LIBS}
if HAVE_RADOS
tests_rados_mobject_connect_test_SOURCES = tests/mobject-connect-test.c
tests_rados_mobject_connect_test_CFLAGS = -DUSE_RADOS
tests_rados_mobject_connect_test_LDADD = -lrados
endif

tests_mobject_client_test_LDADD = src/client/libmobject-store.la ${CLIENT_LIBS}

tests_mobject_aio_test_LDADD = src/client/libmobject-store.la ${CLIENT_LIBS}

