TESTS_ENVIRONMENT += \
 TIMEOUT="$(TIMEOUT)" \
 MKTEMP="$(MKTEMP)"

check_PROGRAMS += \
 tests/mobject-connect-test \
 tests/mobject-server \
 tests/test-sds-keyval-client \
 tests/mobject-client-test

# don't include rados programs in make check
if HAVE_RADOS
noinst_PROGRAMS += \
 tests/rados-mobject-connect-test
endif

TESTS += \
 tests/mobject-connect-test.sh

tests_mobject_connect_test_LDADD = src/client/libmobject-store.la ${CLIENT_LIBS}
if HAVE_RADOS
tests_rados_mobject_connect_test_SOURCES = tests/mobject-connect-test.c
tests_rados_mobject_connect_test_CFLAGS = -DUSE_RADOS
tests_rados_mobject_connect_test_LDADD = -lrados
endif

tests_mobject_client_test_LDADD = src/client/libmobject-store.la ${CLIENT_LIBS}

tests_mobject_server_LDADD = src/server/libmobject-server.la ${SERVER_LIBS}

tests_test_sds_keyval_client_LDADD = ${CLIENT_LIBS}

