src_libmobject_store_la_SOURCES = \
 src/libmobject-store.c \
 src/completion.c \
 src/write-op.c

noinst_HEADERS += src/log.h src/completion.h \
		  src/write-op.h src/write-actions.h\
		  src/utlist.h
